version: "3"

services:
  nginx:
    image: nginx:perl
    restart: always
    volumes:
      - ${routes}:/etc/nginx/conf.d/
    networks:
      api_net:
        ipv4_address: ${nginx_ip}
      domain_net:
        ipv4_address: ${domain_ip}
  
  nats:
    image: nats
    networks: 
      api_net:
        ipv4_address: ${nats_ip}
  
  logs:
    image: vivaconagua/logs-service:stage
    restart: always
    env_file:
      - .env
    links:
      - logs-db:db
      - nats:nats
    env_file:
      - .env
    networks:
      api_net:
        ipv4_address: ${logs_ip}
      db_net:

  logs-db:
    image: mongo
    restart: unless-stopped
    volumes: 
      - ${databases}/logs-db/:/data/db/
    networks:
      db_net:
          
networks:
  api_net:
    external:
      name: api_net
  domain_net:
    external:
      name: domain_net
  db_net:
    external:
      name: db_net
 

    
