#!/bin/bash

print_help_please(){
    echo "Commands: "
    echo "  service        # install deployment scripts."
    echo "  network        # handles docker network." 
    echo "  help           # print this page."
}





case $1 in
    domain)
        ./src/domain.sh  "${@:2}";;
    api)
        ./src/api.sh "${@:2}";;
    nats)
        ./src/nats.sh "${@:2}";;
    logs)
        ./src/logs.sh "${@:2}";;
    frontend)
        ./src/frontend.sh "${@:2}";;
    service) 
        source ${PWD}/src/service && service_handler "${@:2}";;
    network) 
        source ${PWD}/src/network && network_handler "${@:2}";;
    install) 
        ./src/install.sh "${@:2}";;
    link)
         ./src/link.sh "${@:2}";;
    update)
        source ${PWD}/src/update && update_handler "${@:2}";;
    help) 
        print_help_please;;
    *) 
        print_help_please
esac

