#!/bin/bash

touch .env
source .env
source config/helper

print_help_please(){
    echo "Commands: install domain api nats logs frontend network "
    echo "  install         install deployment scripts."
    echo "  network         docker network. "
    echo "  domain          domain please functions"
    echo "  api             api please functions"
    echo "  frontend        frontend please functions"
    echo "  help            print this page."
}
if ! grep -q please-completion.bash ~/.zshrc; then
    cp ~/.zshrc ~/.zshrc.bak-please
    echo source ${PWD}/please-completion.bash >> ~/.zshrc
fi

case $1 in
    base)
        ./base.sh "${@:2}";;
    network) 
        ./network.sh "${@:2}";;
    api)
        ./api.sh "${@:2}";;
    frontend)
        ./frontend.sh "${@:2}";;
    components)
        ./component.sh "${@:2}";;
    quickinstall)
        ./quickinstall.sh "${@:2}";;
    help) 
        print_help_please;;
    *) 
        print_help_please
esac

