#!/bin/bash
# ###
# DOMAIN DEPLOYMENT
source .env
source ../config/helper

current=${PWD}


print_help() {
echo   " Commands: install, link, up, restart, down, logs "
echo   "     install         install domain_service"
echo   "     link            service_name  connect an service and domain"
echo   "     up              create and start service"
echo   "     restart         restarts service"
echo   "     down            delete service docker"
echo   "     logs            get docker logs"
echo   "     help            print this page"
}
# ###
# install_service
install_service() {
    # load config.ini and get default section.
    load_ini && section_ini default
    # create subdomain working directory.
    mkdir -p ${work_dir}/domain/subdomain
    # set .env param subdomain.
    echo subdomain=${work_dir}/domain/subdomain >> .env
    # ask for a path to an if the deploy mode is live.
    echo "#Path to Cert: only used in live mode"
    if [ ${deploy_mode} == "live" ]; then 
        read -e -p "path: " cert_path
        echo "certs="${certs} >> .env
    fi
    # set .env param docker_ip.
    echo docker_ip=${docker_ip} >> .env
    up_service
}

# ###
# link_service
link_service() {
    # loads config.ini and section $1 
    load_ini && section_ini $1
    # store current directory
    current=${PWD}
    # create new nginx config
    case $deploy_mode in
        # in case $deploy_mode == live:
        live) 
            # create a new nginx config in subdomain directory.
            cp ./default.live.conf ${subdomain}/${route}.conf;
            # change current directory to subdomain
            cd ${subdomain};
            # sed certificate in nginx config
            sed -i s/{cretificate}/${certs}/g ${route}.conf;;
        # else:    
        *)  
            # create a new nginx config in subdomain directory.
            cp ./default.dev.conf ${subdomain}/${route}.conf;
            # change current directory to subdomain
            cd ${subdomain};
    esac
    # sed subdomain route in nginx config
    sed -i s/{subdomain}/${route}/g ${route}.conf
    # sed proxy_pass in nginx config
    sed -i s/{proxy_pass}/${docker_ip}/g ${route}.conf
    # change directory to current
    cd $current
    echo $1 is successfully link to domain ${route} with IP: ${docker_ip}.
    # restart_service
    restart_service
}
# ###
# up_service 
up_service() {
    case $deploy_mode in
        live) docker-compose -f docker-compose.yml -f docker-compose.live.yml up -d ;;
        *) docker-compose up -d
    esac
}

# ###
# restart_service
restart_service(){
    case $deploy_mode in
        live) docker-compose -f docker-compose.yml -f docker-compose.live.yml restart ;;
        *) docker-compose restart
    esac
}
# ###
# down_service
down_service(){
    case $deploy_mode in
        live) docker-compose -f docker-compose.yml -f docker-compose.live.yml down ;;
        *) docker-compose down
    esac

}
# ###
# logs_service
logs_service() {
    case $deploy_mode in
        live) docker-compose -f docker-compose.yml -f docker-compose.live.yml "${@:1}" ;;
        *) docker-compose logs "${@:1}"
    esac

}

case $1 in
    install)
        install_service "${@:2}";;
    link)
        link_service "${@:2}";;
    up)
        up_service ;;
    restart)
        restart_service;;
    down)
        down_service;;
    logs)
        logs_service "${@:2}";;
    help)
        print_help;;
    *)
        print_help
esac
