#!/bin/bash


section=""

cfg.parser () {
    temp=$(awk -F '[,[:blank:]]' '{ if ($1 ~ /^\[/) section=$1; print section }' $1| tr ' ' '\n' | sort -u | tr '\n' ' ' | tr '[' ' ' | tr ']' ',')
    IFS=', ' read -r -a sections <<< "$temp"

    fixed_file=$(cat $1 | sed 's/ = /=/g')  # fix ' = ' to be '='
    IFS=$'\n' && ini=( $fixed_file )              # convert to line-array
    ini=( ${ini[*]//;*/} )                   # remove comments
    ini=( ${ini[*]/#[/\}$'\n'cfg.section.} ) # set section prefix
    ini=( ${ini[*]/%]/ \(} )                 # convert text2function (1)
    ini=( ${ini[*]/=/=\( } )                 # convert item to array
    ini=( ${ini[*]/%/ \)} )                  # close array parenthesis
    ini=( ${ini[*]/%\( \)/\(\) \{} )         # convert text2function (2)
    ini=( ${ini[*]/%\} \)/\}} )              # remove extra parenthesis
    ini[0]=''                                # remove first element
    ini[${#ini[*]} + 1]='}'                  # add the last brace
    eval "$(echo "${ini[*]}")"               # eval the result
}

load_config(){
    cfg.parser 'config.ini' &&
        if [ "$(type -t cfg.section.${1})" = 'function' ]; then
            cfg.section.${1}
        else
            echo service not found ${1}
            exit 1
        fi
}

load_ini(){
    cfg.parser 'config.ini'
}

section_ini(){
    if [ "$(type -t cfg.section.${1})" = 'function' ]; then
        cfg.section.${1}
    else
        echo service not found ${1}
    fi
}

load_config_service(){
    path="${root_dir}/config/services.ini"
    echo $path
    cfg.parser $path && 
        if [ "$(type -t cfg.section.${1})" = 'function' ]; then
            cfg.section.${1}
        else
            echo service not found ${1}
            exit 1
        fi
}

load_config_network(){
    cfg.parser '${root_path}/config/network.ini' && 
        if [ "$(type -t cfg.section.${1})" = 'function' ]; then
            cfg.section.${2}
        else
            echo service not found ${1}
            exit 1
        fi
}

load_config_frontend(){
    cfg.parser '${root_path}/config/frontend.ini' && 
        if [ "$(type -t cfg.section.${1})" = 'function' ]; then
            cfg.section.${2}
        else
            echo service not found ${1}
            exit 1
        fi
}
