version: "3"

services:
    nginx:
        image: nginx:perl
        restart: always
        volumes:
            - ${api_v1_path}:/etc/nginx/conf.d/
        networks:
            api_net:
                ipv4_address: ${api_net_ip}
            domain_net:
                ipv4_address: ${domain_net_ip}
  
networks:
  api_net:
    external:
      name: api_net
  domain_net:
    external:
      name: domain_net
 

    
