#!/bin/bash

print_help(){
    echo "Commands: base, payment "
    echo "                 # install base"
    echo "  base           # install base"
    echo "  payment        # install payment"
}

if [ -z ${1} ]; then
    ./base.sh exit;
else
    case $1 in
        base)
            ./base.sh;;
        payment)
            ./payment.sh;;
        *)
            print_help
    esac
fi
