#!/bin/bash

init_handler() {
    echo "Init please script."
    echo "Create .env file for environment variables."
    echo "Add workdir path: "
    read workdir
    mkdir -p workdir
    echo "# work directories"
    echo "work_dir=${workdir}"
    echo "volumes_dir=${workdir}/volumes" > .env
    echo "repos_dir="${workdir}/repos >> .env
}
