#!/bin/bash

init_handler() {
    echo "Init please script."
    echo "Create .env file for environment variables."
    echo "Add volumes path: "
    read volumes
    echo "volumes="${volumes} > .env
    echo "Add repos path: "
    read repos 
    echo "repos="${repos} >> .env
}
