#!/bin/bash


install_completions() {
    if ! grep -q please-completion.bash ~/.zshrc; then
        cp ~/.zshrc ~/.zshrc.bak-please
        echo source ${PWD}/src/complete/please-completion.bash >> ~/.zshrc
    fi
}

install_env() {

    read -e -p "Please add a work directory path: " work_dir
    mkdir -p ${work_dir%/}/volumes ${work_dir%/}/repos
    echo "# work directories"
    ip=(develop)
    while true; do
        read -e -i "n" -p "Do you wish to install in live mode [y/N]: " yn
        case $yn in
            [Nn]* ) echo deploy_mode=develop > .env; break;;
            [Yy]* ) echo deploy_mode=live > .env; break;;
            * ) echo "Please answer y or n.";;
        esac
    done
    echo "work_dir=${work_dir%/}" >> .env
    echo "volumes_dir=${work_dir%/}/volumes" >> .env
    echo "repos_dir="${work_dir%/}/repos >> .env
}
install_handler() {
    clear
    echo "#################################"
    echo "#                               #"
    echo "###      Install please       ###"
    echo "# viva con agua deployment tool #"
    echo "#                               #"
    echo "#################################"
    echo ""
    install_completions
    install_env
    echo please has successfully installed
}
