#!/bin/bash

source ${PWD}/config/helper
source .env

link_service_api(){
    load_config_service $1
    ip=${api_net_ip}
    rt=${route}
    load_config_service api
    cd $repos_dir/$repo_name &&
    ./please link $1 $ip $rt
}


case $1 in
    api)
        link_service_api $2;;
    *)
esac
