#!/bin/bash



source ${PWD}/config/helper



create_network(){
    cfg.parser './config/network.ini' && cfg.section.${1} &&
    docker network create -d bridge --subnet ${subnet} ${name} || true

}

delete_network(){
    cfg.parser './config/network.ini' && cfg.section.${1} &&
    docker network rm ${name}
}


info_print(){
    cfg.section.${1} &&
    echo "Name: ";
    docker network inspect ${name} --format "{{.Name}}"; 
    echo "Subnet: ";
    docker network inspect ${name} --format "{{range  .IPAM.Config}}{{println .Subnet}}{{end}}";
    echo "Container Names and IPv4Addresses: ";
    docker network inspect ${name} --format "{{range  .Containers}}{{println .Name .IPv4Address}}{{end}}"; 
}

info_network(){
    cfg.parser './config/network.ini' &&
    if [ -z ${1+x} ]; then
        for v in ${section[*]}
        do
            info_print $v
        done
    else
        info_print $1
    fi
}

network_handler () {
    case $1 in
        create) create_network $2;;
        delete) delete_network $2;;
        info) info_network $2;;
    esac
}
