#!/bin/bash



source ${PWD}/config/helper



create_network_function(){
    cfg.parser './config/network.ini' && cfg.section.${1} &&
    docker network create -d bridge --subnet ${subnet} ${name} || true

}
create_network(){
    cfg.parser './config/network.ini' &&
    if [ -z ${1} ]; then
        for v in ${sections[*]}
        do
            create_network_function $v
        done
    else
        create_network_function $1
    fi

}

delete_network(){
    cfg.parser './config/network.ini' && cfg.section.${1} &&
    docker network rm ${name}
}


info_print(){
    cfg.section.${1} &&
    echo "Name: ";
    docker network inspect ${name} --format "{{.Name}}"; 
    echo "Subnet: ";
    docker network inspect ${name} --format "{{range  .IPAM.Config}}{{println .Subnet}}{{end}}";
    echo "Container Names and IPv4Addresses: ";
    docker network inspect ${name} --format "{{range  .Containers}}{{println .Name .IPv4Address}}{{end}}"; 
}

info_network(){
    cfg.parser './config/network.ini' &&
    if [ -z ${1+x} ]; then
        for v in ${sections[*]}
        do
            info_print $v
        done
    else
        info_print $1
    fi
}

set_network(){
        cfg.section.${1}
        net="${2}_ip"
        echo $api_ip
        if ! grep -q $net .env ; then
            sed '/${net}/d' .env
        fi
        echo ${!net}
        echo ${net}
        echo ${net}=${!net} >> .env

}

set_networks(){
    cfg.parser './config/network.ini' &&
    for var in ${sections[*]}
    do
        set_network $var ${1}
    done
}

network_handler () {
    case $1 in
        create) create_network $2;;
        delete) delete_network $2;;
        set) set_networks $2;;
        info) info_network $2;;
        rm) delete_network $2;;
    esac
}


