#!/bin/bash

source ${PWD}/config/helper
source .env



install_service() {
    cfg.parser './config/services.ini' && cfg.section.${1} &&
    cfg_path=${PWD}/config
    cd $repos_dir &&
    if ! [ -d $repo_name ] ; then
        git clone $repo
    fi
    cd $repo_name
    echo deploy_mode=${deploy_mode} > .env
    ./please install $cfg_path $work_dir
}

up_service(){
    cfg.parser './config/services.ini' && cfg.section.${1} &&
    cd $repos_dir/$repo_name &&
    ./please up $1
}





test_service(){
    cfg.parser './config/services.ini'
    echo $(cfg.section.${1})
    output=$(awk -F ' *= *' '{ if ($1 ~ /^\[/) printf "\n" $1; else if ($1 !~ /^$/) printf $1 "="  $2  }' config/network.ini | grep "\[domain\]")
    echo $output
    IFS=', ' read -r -a section <<< "$output"
    for var in ${section[*]}
    do
        echo $var
    done

    
}

print_help_install() {
    echo "only provide services: "
    echo "domain"
}

service_handler() {
    case $1 in
        install) 
            install_service $2;;
        up)
            up_service $2;;
        test)
            test_service $2;;
        link)
            link_service $2 $3;;
        *) 
            print_help_install
    esac
}
