version: '3'

services:
    nginx:
        image: nginx
        restart: unless-stopped
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ${subdomain_path}/:/etc/nginx/conf.d/subdomain/
        ports:
            - 80:80
        networks:
            default:
                ipv4_address: ${domain_net_ip}


networks:
  default:
    external:
      name: domain_net  
